"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class SimHandler(object):
    __slots__ = ["timestamp", "handler", "parameters"]

    def __init__(self):
        self.timestamp = 0
        self.handler = 0
        self.parameters = ""

    def encode(self):
        buf = BytesIO()
        buf.write(SimHandler._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.handler))
        __parameters_encoded = self.parameters.encode('utf-8')
        buf.write(struct.pack('>I', len(__parameters_encoded)+1))
        buf.write(__parameters_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != SimHandler._get_packed_fingerprint():
            raise ValueError("Decode error")
        return SimHandler._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = SimHandler()
        self.timestamp, self.handler = struct.unpack(">qi", buf.read(12))
        __parameters_len = struct.unpack('>I', buf.read(4))[0]
        self.parameters = buf.read(__parameters_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if SimHandler in parents: return 0
        tmphash = (0x68413874837bcf9b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if SimHandler._packed_fingerprint is None:
            SimHandler._packed_fingerprint = struct.pack(">Q", SimHandler._get_hash_recursive([]))
        return SimHandler._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

